### ISSUE TITLE
Hide dotfiles by default in Save As dialog if possible

### ISSUE THREAD

**Issue by dmalan** [cs50/codespace#10]
<img width="751" alt="Screen Shot 2021-06-26 at 4 23 46 PM" src="https://user-images.githubusercontent.com/788678/123524852-f34ab800-d69a-11eb-8cc0-0194e0f98544.png">

**Comment by rongxin-liu** [comment]
Not seeing related post at the moment, so I filed a bug report instead:
[https://github.com/microsoft/vscode/issues/136307](https://github.com/microsoft/vscode/issues/136307)

**Comment by dmalan** [comment]
Commented on report!
