### ISSUE TITLE
Initiation

### ISSUE THREAD

**Issue by Druggan-P** [cs50/codespace#102]
The instructions don't seem to reflect reality

1) Submit [this form](https://forms.cs50.io/27a35e60-490a-4e42-8574-6b55154ae760).
2) Visit [this link](https://submit.cs50.io/invites/579861a2825849178cd11315c055bc49), log in with your GitHub account, and click Authorize CS50.
3) Check the box indicating that you’d like to grant course staff access to your submission, and click Join course.
4) Log into [code.cs50.io](https://code.cs50.io/), which is a cloud-based version of Visual Studio Code (VS Code) that provides you with your very own “codespace” with everything that you need for the course pre-installed. No need to download and install VS Code or Python on your own Mac or PC!
5) Once your codespace has loaded, close any Welcome tabs that might have opened by default
Execute update50 in your codespace’s terminal window to ensure that your codespace is up-to-date; if prompted, click Rebuild now.

Firstly you need to use more white space between the instructions in the list.  I'm dyslexic with ADHD. To put this in context though I have a PhD in Pharmacy and I'm a subject matter expert in statistics among other subjects

I have got to step four. Logged in to CS50 codespace. This opens the desktop. Now this is where the instructions are incomplete .

No welcome tabs came up - not an issue. so 5) is redundant here.

Then we leap to 6) Execute update50 in your codespace’s terminal window - where is this? 
I click on codespace and get a directory, not a functional work space.

If I am supposed to click on the green <code> button on the right, this is not obvious to left-hand right-hand readers.

Apologies if this sounds pedantic, but I have been writing instructions for use and SOPs for 35 years.

These days I would have made a desktop video for this. 

I might do it anyway.

**Comment by rongxin-liu** [comment]
Thank you very much for your feedback. May we know which CS50 course you are taking exactly? Which course website are you looking at? If you are taking CS50 online (e.g., CS50x), this instruction seems to be obsolete, and we're curious where you see this instruction.

Though to address your concern, here are some contexts:
Step 5 is not redundant, as there would be a case a welcome tab would actually come up. The message is meant to cover unforeseeable VS Code behavior which we have incurred during testing, hence the wording "close ... that might have opened".
For step 6, we meant to have the user type "update50" in the terminal. If a student has watched our week one lecture, they should know what we meant by saying "execute" (e.g., typing a command in the terminal and running it). Perhaps we can be redundant and make it explicitly clear by emphasizing they should "type update50 in the terminal".

**Comment by Druggan-P** [comment]
Thank you for getting back so promptly. It is for CS50P. 

 

The teaching is very good, so much so that I’ve been through three or four weeks in as many days, and I am actually motivated to do homework.

 

I  can’t get to the terminal, so there is an information gap between 5 and 6
