### ISSUE TITLE
https://druggan-p-automatic-space-giggle-v6vgvv6q5497fw674.github.dev/

### ISSUE THREAD

**Issue by Druggan-P** [cs50/codespace#103]
Hangs for a long time creating the codespace.

Finally gives an error.

Screenshot attached
[installation error 2023-07-23.docx](https://github.com/cs50/codespace/files/12138352/installation.error.2023-07-23.docx)

**Comment by rongxin-liu** [comment]
Duplicated:
https://github.com/cs50/codespace/issues/105
