### ISSUE TITLE
Initiation - missing pieces

### ISSUE THREAD

**Issue by Druggan-P** [cs50/codespace#104]
Github creates codespaces even though there is an error

The issue is that you have no explanation that a message will be sent to the email account.

This is the "welcome" I assume you had originally and has been superceeded by an email "invitation"

Once you click on this you get https://github.com/me50/Druggan-P

Yaay!

Then you get a message saying you have created too many codespaces. 
That was easy to sort out, but I have been trying to do the Problem 0 set for the past 90 minutes and not written a single line of code.

**Comment by Druggan-P** [comment]
Please remember that human error is due to two things:

Bad management or bad design

**Comment by rongxin-liu** [comment]
The "invitation" email is not the same "welcome tab" we mentioned in the obsolete instructions. Did you happen to create a codespace on your me50 repository? I don't think we have instructions telling students to create any codespaces other than using https://cs50.dev (previously known as code.cs50.io).

Problem set 0 (Scratch) indeed doesn't require the use of codespace and writing any codes. Are you also encountering issues with Scratch?

**Comment by Druggan-P** [comment]
Went to https://cs50.dev 

 

Click on codespace. Unless I am meant to clink on special chainsaw for the input code, I have nowhere to put update50

**Comment by Druggan-P** [comment]
Connected through “special chainsaw” and get the same error. Though the terminal is beneath the error message.

**Comment by Druggan-P** [comment]
Tried in Google Chrome

**Comment by Druggan-P** [comment]
This looks like a settings issue my end, but I would need details of the ports to sort this out.
