### ISSUE TITLE
Well, maybe not

### ISSUE THREAD

**Issue by Druggan-P** [cs50/codespace#105]
![image](https://github.com/cs50/codespace/assets/140306186/b78fffa7-486e-4a03-b9dd-aaaf62d92cb3)

**Comment by rongxin-liu** [comment]
GitHub is aware of this issue, and whey should address it soon. Please note that we do not manage Codepsaces, so we can't solve this problem.

A workaround would be to visit cs50.dev/restart to restart your codespace and see if that fixes the issue.

**Comment by Druggan-P** [comment]
Not a problem. This is feedback not complaint or accusation.
