### ISSUE TITLE
me50

### ISSUE THREAD

**Issue by Druggan-P** [cs50/codespace#106]
Get the same error in me50

**Comment by rongxin-liu** [comment]
Could you please describe your issue in detail and attach screenshots?

**Comment by Druggan-P** [comment]
I did when I raised the issue. A screen shot was pasted in.

**Comment by dmalan** [comment]
Best to reach out to sysadmins@cs50.harvard.edu with questions like these.

**Comment by Druggan-P** [comment]
Thanks. This is feedback for you. I’m not going for the credit. I’ll code it in the IDE, I don’t need a mark.

 

You do a good job with the lectures. I’ve really enjoyed them. I think I’m on week four in as many days.

 

Patrcik
