### ISSUE TITLE
Move patch file for `http-server` to `cs50/cli`

### ISSUE THREAD

**Issue by rongxin-liu** [cs50/codespace#124]

**Comment by dmalan** [comment]
What's the motivation for this one, @rongxin-liu, to rewrite the outputted URL with whatever port Docker is mapping to on the host?

**Comment by rongxin-liu** [comment]
No strong feeling, just wanted to keep everything in one place:
https://github.com/cs50/cli/blob/main/Dockerfile#L169-L170

**Comment by dmalan** [comment]
https://github.com/cs50/cli/pull/187
