### ISSUE TITLE
When A uses Live Share to share a collaboration URL with B, and A sends a chat message, B doesn't see any chat messages

### ISSUE THREAD

**Issue by dmalan** [cs50/codespace#15]
User B sees:

<img width="1536" alt="Screen Shot 2021-06-26 at 4 47 46 PM" src="https://user-images.githubusercontent.com/788678/123525399-57bb4680-d69e-11eb-9950-f41d63aa2de6.png">

**Comment by CarterZenke** [comment]
![chat](https://user-images.githubusercontent.com/5281090/123525420-80dbd700-d69e-11eb-9b38-67c1ca14c971.PNG)

**Comment by dmalan** [comment]
Able to reproduce this one, @rongxin-liu?

**Comment by rongxin-liu** [comment]
Session Chat is working as expected, closing this issue now.

**Comment by dmalan** [comment]
Thanks!
