### ISSUE TITLE
Installation Failure for face_recognition due to dlib Build Error

### ISSUE THREAD

**Issue by z-my-cn** [cs50/codespace#155]
### Environment

- CS50 Codespace
- Python version: 3.12.4
- pip version: 24.1

### Issue Description

I am attempting to install the `face_recognition`  package in the CS50 Codespace, but the installation fails when building the `dlib` package. The error message indicates that CMake is not installed, which is required for building `dlib`.

### Steps to Reproduce

1. Open the CS50 Codespace.
2. Run the command: `pip install face_recognition`.

### Expected Behavior

The `face_recognition` package should install successfully along with all its dependencies, including `dlib`.

### Actual Behavior

The installation process fails when attempting to build the dlib package. Here is the relevant part of the error output:

```
Building wheels for collected packages: dlib, face-recognition-models
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      <string>:196: SyntaxWarning: invalid escape sequence '\('
      <string>:197: SyntaxWarning: invalid escape sequence '\('
      <string>:198: SyntaxWarning: invalid escape sequence '\('
      running bdist_wheel
      running build
      running build_ext
      
      ERROR: CMake must be installed to build dlib
      
      [end of output]
```

**Comment by rongxin-liu** [comment]
Please try running these commands to install `face_recognition` to your Codespace:

```bash
sudo apt-get install cmake libx11-dev libopenblas-dev liblapack-dev libpng-dev pkg-config
pip install face_recognition 
```
