### ISSUE TITLE
GUI Button no longer seems to work

### ISSUE THREAD

**Issue by stephendgilbert** [cs50/codespace#158]
In cs50.dev the GUI button on the CS50 menu used to open a GUI window. It no longer seems to work (but this is the first time I've looked at it this semester.) Here's what shows up in the browser's console. I've tried in Chrome, Edge and Firefox.
![image](https://github.com/user-attachments/assets/409a3c46-da0f-4a14-bdc2-33c55a1b1937)

**Comment by rongxin-liu** [comment]
Hi, are you running Codespace in a campus environment or somewhere else?

I just tried it on my end, and I was able to open the GUI window. Have you tried running `update50 --force` to rebuild your codespace?

**Comment by stephendgilbert** [comment]
I am running it on our campus. (I mean, of course, that I'm accessing it on my campus; I assume that it's actually running somewhere else on the GitHub servers.)

**Comment by stephendgilbert** [comment]
Hello, I don't know if any changes were made, but today, it starts right up.
