### ISSUE TITLE
Are there any VS Code existing extensions that we could use or model our own on that would display an alert to a user when an update's available, a la our StatusPage JS plugin?

### ISSUE THREAD

**Issue by dmalan** [cs50/codespace#19]

**Comment by rongxin-liu** [comment]
Yes, our extension can read that and [this commit](https://github.com/cs50/cs50.vsix/commit/7cb614a17a9d7a84ae6483b168f9bfa7dad584c9) adds support to prompt user when a new update is available:

<img width="669" alt="Screen Shot 2021-11-06 at 03 26 52" src="https://user-images.githubusercontent.com/10591665/140601753-60d7f45e-71d9-44ed-ba1d-d41f2a681e1f.png">

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/cs50.vsix/commit/7cb614a17a9d7a84ae6483b168f9bfa7dad584c9](https://github.com/cs50/cs50.vsix/commit/7cb614a17a9d7a84ae6483b168f9bfa7dad584c9)
