### ISSUE TITLE
.devcontainer settings object is not active in CS50 codespace

### ISSUE THREAD

**Issue by bhorsey1** [cs50/codespace#31]
After launching a fresh environment is CS50, the .devcontainer settings that are deployed do not actually affect the environment itself once launched.

.vscode/settings.json is an empty object (ie {})

Redeploying did not seem to have an effect.

Is this the desired behavior?

**Comment by dmalan** [comment]
Remote settings end up in `/home/ubuntu/.vscode-remote/data/Machine/settings.json`!
