### ISSUE TITLE
Intelli-Sense for c++

### ISSUE THREAD

**Issue by mkotsovoulou** [cs50/codespace#44]
Hello again...
Although the C/C++ extension is enabled in code.cs50.io, intelli-sense does not seem to work to propose methods after the dot . 
I am getting ...no suggestions even with ctrl-space.
I have tried using all different versions of compilers and intelli-sense options....
I am doing something wrong? or it is disabled from the container?
Thank you for reading this!
Maira K.

**Comment by dmalan** [comment]
It's indeed disabled for pedagogical reasons, but you can re-enable if you'd like!

https://cs50.readthedocs.io/code/#settings
