### ISSUE TITLE
Path to code binary has changed

### ISSUE THREAD

**Issue by loryeam** [cs50/codespace#45]
When running `code` command I get the following error:
```bash
$ code
/opt/cs50/bin/code: line 52: /vscode/bin/linux-x64/5554b12acf27056905806867f251c859323ff7e9/bin/code: No such file or directory
```
I can reproduce the issue on fresh instances of codespace.
This patch should fix it:
```patch
diff --git a/opt/cs50/bin/code b/opt/cs50/bin/code
index 04d5acb..bb9a4fe 100755
--- a/opt/cs50/bin/code
+++ b/opt/cs50/bin/code
@@ -49,4 +49,4 @@ if [ "$options" = false ]; then
     done
 fi
 
-$(dirname "$VSCODE_GIT_ASKPASS_NODE")/bin/code "$@"
+$(dirname "$VSCODE_GIT_ASKPASS_NODE")/bin/remote-cli/code "$@"
```

**Comment by rongxin-liu** [comment]
@loryeam Thank you for reporting! Should now be fixed!

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/codespace/commit/07d9d6ec4042cdf354231217f004cb96c1898ed4](https://github.com/cs50/codespace/commit/07d9d6ec4042cdf354231217f004cb96c1898ed4)

**Comment by loryeam** [comment]
Thank you! The issue seems to be fixed after getting latest version using `update50` and rebuilding the codespace.
