### ISSUE TITLE
502 Bad Gateway - unable to create codespace 

### ISSUE THREAD

**Issue by Melkor118** [cs50/codespace#49]
I was experiencing some issues with my codespace not syncing the extensions correctly and communicating with github after accidentally removing the .devcontainer.json file.

Tried a few things to fix it:

- rebuilding the codespace.
- deleting the codespace and getting a new one.
- manually adding a .devcontainer.json with code retrieved from another code50 instance.

Eventually I thought perhaps if I leave the code50 organisation and try to start fresh with the same github account (this one) it would fix it.

I have left the code50 organisation but now when I try to create a new codespace from code.cs50.io it gives me a Bad Gateway error. 

I'm guessing it's probably regarding the organisation status since it's failing before it allows me to connect my github to the organisation.

When using a new github account it works fine but I would love to not have to change github accounts.

Any assistance would be appreciated.

**Comment by rongxin-liu** [comment]
Please accept the invite to rejoin code50 organization, then try creating a new Codespace at [code.cs50.io/settings](code.cs50.io/settings).

**Comment by Melkor118** [comment]
Awesome, that's done it. Thank you so much, really appreciate the quick assistance.

**Comment by Omar-Badr145** [comment]
I was experiencing the exact same issue, I was wondering how to rejoin the code50 organization.
