### ISSUE TITLE
Accessing code.cs50.io always gives a Bad Gateway error

### ISSUE THREAD

**Issue by mimarque** [cs50/codespace#51]
Trying to access code.cs50.io on Safari, Chrome or Firefox always gives out "Bad Gateway Could not create codespace" error after clicking on "Login via github" even if you check "Open in VS Code Desktop".

It makes it impossible to do any work if not locally.

**Comment by rongxin-liu** [comment]
Please accept the invite to join code50 org, thanks!

**Comment by mimarque** [comment]
Thank you. Can you explain what exactly was the issue?

**Comment by abe-101** [comment]
I'm having the same issue. I keep getting a bad gateway.
When I click the invite linkit redirects me to: https://github.com/me50/abe-101 with no option to accept the invite.

**Comment by rongxin-liu** [comment]
> [abe-101](/abe-101)

You seemed to have left the code50 organization. Please accept the invite to rejoin code50 org then try again.

**Comment by abe-101** [comment]
Makes sense. I must have lseft after completing cs50x.
Thank you for reinviting me. Really apriciate it! and I'm really liking the new python course!

**Comment by djknafler** [comment]
could I have an invite also? I removed myself by accident.

**Comment by rongxin-liu** [comment]
> could I have an invite also? I removed myself by accident.

Please email [sysadmins@cs50.harvard.edu](sysadmins@cs50.harvard.edu) with your GitHub username and a screenshot of the issue.
