### ISSUE TITLE
Bad Gateway Error on code.cs50.io

### ISSUE THREAD

**Issue by ilyesm** [cs50/codespace#54]
Hi there!

I am a 2021 student, trying to login to code.cs50.io, following the steps to migrate my files from the IDE to VS Code. I am unable to login, as I get a 502 Bad Gateway error.

GET https://code.cs50.io/open?code=********* 502 (Bad Gateway)

From reading past issues on GitHub, I see that I probably need to be invited to the CS50 org? If so, this is my GitHub account!

Thanks!

**Comment by rongxin-liu** [comment]
Please email `sysadmins@cs50.harvard.edu` with your GitHub username. Thank you!
