### ISSUE TITLE
Unable to Launch VNC

### ISSUE THREAD

**Issue by orsenthil** [cs50/codespace#60]
I am excited to see this codespace project and ablity to natively work with codespace using VSCode.

I tried it with my VSCode, was able to test a program.

![image](https://user-images.githubusercontent.com/332330/180617418-26b7de97-97b7-4fd2-b7a7-d1fa88068573.png)

I tried to launch GUI, but it failed to connect to the server.

![image](https://user-images.githubusercontent.com/332330/180617442-4c8915da-2a39-4aca-9db7-01fb5b994dfa.png)

* How should I troubleshoot?
* I couldn't find anything in the logs `docker logs`.

**Comment by rongxin-liu** [comment]
Are you launching the GUI in the browser?

**Comment by orsenthil** [comment]
> Are you launching the GUI in the browser?
Yes.

>  If running on the Docker container offline, it is not supported currently.
Oh I see. So, only from code.cs50.io is it?

**Comment by orsenthil** [comment]
How do I try launch gui on code.cs50.io ? It failed even earlier.

![image](https://user-images.githubusercontent.com/332330/180631260-283d91f1-5733-4017-8f13-3594f055df9b.png)

**Comment by rongxin-liu** [comment]
Is your browser blocking pop-ups? You could try visiting code.cs50.io/restart to restart your Codespace, then try launching the GUI again. It would open a separate tab/window.
![Screen Shot 2022-07-23 at 21 17 50](https://user-images.githubusercontent.com/10591665/180633126-770c63c3-5390-41fe-98b0-c27696b151f3.png)
