### ISSUE TITLE
Rely on `which -a code` instead of `VSCODE_GIT_ASKPASS_NODE` to find `code`

### ISSUE THREAD

**Issue by dmalan** [cs50/codespace#64]
1. Eliminate https://github.com/cs50/codespace/blob/e3e85cef24fb5470585231ba16175b3b5060e45b/etc/profile.d/codespace.sh#L37-L39, since `/opt/cs50/bin` already seems to have higher precedence in `PATH`?
2. Parse `which -a code` to get path to `code`

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/codespace/commit/75e0e1d9140e427d0135d843bd3a7a2282a27f63](https://github.com/cs50/codespace/commit/75e0e1d9140e427d0135d843bd3a7a2282a27f63)
