### ISSUE TITLE
Cursor Absent

### ISSUE THREAD

**Issue by Raniahtm** [cs50/codespace#68]
Hello,

I am trying to check the code I have developed for Exercise 6, Scarify. I am accessing CodeSpace via the web. Unfortunately, the cursor is not available on the screen and I can't write anything in the box. At the same time, the $ prompt is visible. I have been prompted to rebuild the container multiple time in vain. Appreciate your support to provide a solution. Looking forward to your response and thank you in advance. 

Best Regards,
Rania.

**Comment by rongxin-liu** [comment]
Please report this issue at https://github.com/microsoft/vscode/issues.

Please try this:

- Click the Settings icon (the gear icon on the bottom-left icon)
- Search for "terminal.integrated.gpuAcceleration"
- Click "Workspace"
- Set it to "off"

<img width="940" alt="gpu_rendering" src="https://user-images.githubusercontent.com/10591665/200311804-4cde7c11-616e-44fd-8bbc-cdd82832a340.png">

**Comment by rongxin-liu** [comment]
https://github.com/microsoft/vscode/issues/165416
