### ISSUE TITLE
`case` statements aren't indented by `style50`

### ISSUE THREAD

**Issue by dmalan** [cs50/codespace#94]
```
#include <stdio.h>

int main(void)
{
    int x;
    switch (x)
    {
    case 1:
        printf("");
        break;
    case 1:
        printf("");
        break;
    }
}
```

**Comment by dmalan** [comment]
Before we retool `style50` per other thread, should we update current version with latest https://github.com/cs50/codespace/blob/f3fc84789e0b8386f8172fb784340fefdf065514/.devcontainer.json#L42 value?

**Comment by rongxin-liu** [comment]
Not a bug, changes aren't being deployed to main yet.

**Comment by rongxin-liu** [comment]
https://github.com/cs50/codespace/commit/f3fc84789e0b8386f8172fb784340fefdf065514
